name: FIDASIM_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy=1.26.4
  - scipy=1.12.0
  - matplotlib=3.8.4
  - scikit-image=0.22.0
  - h5py=3.9.0
  - networkx=3.1
  - pillow=10.2.0
  - packaging=23.2
  - pyparsing=3.0.9
  - six=1.16.0
  - cycler=0.11.0
  - contourpy=1.2.0
  - kiwisolver=1.4.4
  - fonttools=4.25.0
  - tornado=6.3.3
  - pyqt=5.15.10
  - sip=6.7.12
  - pyqt5-sip=12.13.0
  - qt-main=5.15.2
  - tbb=2021.8.0
  - ply=3.11
  - mysql=5.7.24
  - cfitsio=3.470
  - imageio=2.33.1
  - imagecodecs=2023.1.23
  - tifffile=2023.4.12
  - zlib
  - bzip2
  - xz
  - lz4-c
  - zstd
  - tk
  - readline
  - sqlite
  - openssl
  - ca-certificates
  - pip:
      - f90nml==1.4.4
